//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simple_Face_Recognition_App.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMAGENES
    {
        public int CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public byte[] IMAGEN { get; set; }
    }
}
