//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public int CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public string CORREO { get; set; }
        public string DEPARTAMENTO { get; set; }
        public string CARGO { get; set; }
    
        public virtual DEPARTAMENTOS DEPARTAMENTOS { get; set; }
    }
}
